### ISSUE TITLE
Python standard library?

### ISSUE THREAD

**Issue by ericvsmith** [benjamin-bader/aiosmtp#2]
Ben:

A group of us are interested in writing an asyncio-based smtpd server. I realize your code isn't complete, but it would save us some time if we used it as a starting point. Our goal is to get this included in python 3.6's standard library. Since you're already using the Apache license, there shouldn't be any problem.

Would you be okay with us using your code as part of this effort?

We've already done some work on an smtpd server:
https://gitlab.com/python-smtpd-hackers/aiosmtpd

Here's the Python contributor form, which you'd need to sign:
https://www.python.org/psf/contrib/contrib-form/

Here is the python bug report that discuss this effort: http://bugs.python.org/issue25008

I think most of us involved in this effort are nosy on that bug.

Thanks, and let me know your thoughts.
Eric.

**Comment by benjamin-bader** [comment]
As you note, this project is Apache-licensed, and thus you are free to use the code as you wish accordingly.

If and when the time comes for merging, I'll be happy to look over the contributor agreement.

Thanks for reminding me of this project - glad to have someone pick it up again.
